backend:
  name: github
  repo: derrickshowers/d5k-thoughts
  branch: master
publish_mode: editorial_workflow

# Images
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Collections
collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
